apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-react-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: custom-react-app
  template:
    metadata:
      labels:
        app: custom-react-app
    spec:
      containers:
      - name: custom-react-app
        image: custom-react-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
