apiVersion: v1
kind: Service
metadata:
  name: custom-react-app-service
spec:
  type: LoadBalancer
  selector:
    app: custom-react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
